### ISSUE TITLE
Ansible is not installing Wordpress properly

### ISSUE THREAD

**Issue by SimonRefslund** [Nicl0996/wordpress-ansible#25]
Franklin and Simon will fix this.

**Comment by C4V3** [comment]
How long will this take?

**Comment by SimonRefslund** [comment]
as long as we need

**Comment by SimonRefslund** [comment]
i think to proper category for this specific issue is "Mis-configuration" or "typo" it is not a bug at all. AT ALL

**Comment by SimonRefslund** [comment]
CAN WE PLZ GET THE TEMPLATE FOR DOING PULL REQUEST, SO THE HYSTERICAL ADMINS WILL FINALLY ACCEPT

**Comment by C4V3** [comment]
![40253 original-1980](https://cloud.githubusercontent.com/assets/18348648/15208816/01dbbcba-182e-11e6-975b-54b41819ef67.jpg)
