### ISSUE TITLE
Progress in PHP

### ISSUE THREAD

**Issue by Abendon** [Nicl0996/wordpress-ansible#26]
Hugo and Balint started to work on PHP, we leave comments here about the problems/issues we have.

**Comment by Abendon** [comment]
We could not manage to test it, because it misses the hosts.

**Comment by Abendon** [comment]
ansible-playbook main.yml

ERROR: provided hosts list is empty

this is the error we get.

**Comment by moozer** [comment]
Could you supply some more info?

log save the ansible/vagrant output to a log file and attach it to a comment
