### ISSUE TITLE
Describe integration test

### ISSUE THREAD

**Issue by wartexth** [Nicl0996/wordpress-ansible#28]
Making a description how the user can test if the "product" works.
Morten and David.

**Comment by moozer** [comment]
How to get IP address of vagrant server
vagrant ssh-config

to automate
moz@lennart:/mnt/storage/moz/git/CTF-system/tests$ IP=$(vagrant ssh-config gameserver | grep HostName | cut -d ' ' -f 4)
moz@lennart:/mnt/storage/moz/git/CTF-system/tests$ w3m http://$IP/
:-)

**Comment by C4V3** [comment]
This issue is still being developed.

**Comment by C4V3** [comment]
If you could remove the "(2nd Semester)" thing in the README.md next time you make a pull request, that would be wonderful.

**Comment by wartexth** [comment]
put on hold for now

**Comment by moozer** [comment]
On hold for when?
