### ISSUE TITLE
vagrant up error

### ISSUE THREAD

**Issue by moozer** [Nicl0996/wordpress-ansible#9]
I noticed that "Vagrantfile" had appeared, so I tried to do "vagrant up". It fails.

> $ vagrant up
> Bringing machine 'default' up with 'libvirt' provider...
> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> ansible provisioner:
> - `playbook` for the Ansible provisioner does not exist on the host system: /home/its/vagrant-prov/wordpress-ansible/playbook.yml

How is it supposed to work?
Perhaps @C-T-E can clarify?

**Comment by C4V3** [comment]
C-T-E has created a new Vagrant file and it has been merged.
